### PR TITLE
added more descriptive EDA, followed Tiffany's example

### PR DESCRIPTION
**Pull request by katieb1**
* Added more descriptions of the data by following chapter 4 of the Art of Data Science
* Made into more of a "report-style", following Tiffany's example
* Still need to add a few things such as figure/table captions, make table look nicer, group similar figures together into single figure

### CODE REVIEW

**Comment by techrah** [comment]
For the section entitled "Do people buy their avocados in bags more or individually?", the scale of the graph on the X-axis looks incorrect. Please confirm.

image

**Comment by katieb1** [comment]
The x-axis is correct, people just bought a lot of avocados.

**Comment by katieb1** [comment]
I'm probably going to get rid of this plot anyway because it doesn't have to do with our research question.

**Comment by techrah** [comment]
Great. Thanks!

**Pull request merged**
